<?php

    define('LANGTXT', array(
            'select'                            => 'Select',
            'edit'                              => 'Edit',
            'delete'                            => 'Delete',
            'telephone'                         => 'Telephone',
            'error-register'                    => 'That email is already associated with another account.',
            'error-login'                       => 'Incorrect user or password.',
            'user-fail'                         => 'This user does not have access permissions.',
            'error-login-admin'                 => 'Incorrect user or password.',
            'user-admin-fail'                   => 'This user does not have access permissions.',
            'newsletter-ok-title'               => 'Registration completed successfully',
            'newsletter-ok-description'         => 'We have sent an email to your account to confirm your subscription to the newsletter. Check your spam folder if you cant find the email.',
            'error-view-title'                  => 'View not found',
            'error-view-description'            => 'The view you are trying to display does not exist.',
            'error-ddbb-title'                  => 'Failed to connect to the database',
            'error-ddbb-description'            => 'Check that the connection variables are correct in the file <b>app/config/config.php</b>.',
            'error-query-title'                 => 'Query failed',
            'error-query-description'           => 'An error has occurred when performing the query to the database, check the parameters.',
            'send-notify-stock'                 => 'Your request has been registered correctly!',
            'new-address'                       => 'You need to create a new shipping address.',
            'new-billing-address'               => 'You need to create a new billing address.',
            'delete-from-cart'                  => 'Remove from cart.',
            'cart-empty'                        => 'Your cart is empty.',
            'newsletter-validation-ok'          => 'Your account has been successfully validated.',
            'newsletter-validation-ko'          => 'Your account could not be validated.',
            'apply-code-ok-title'               => 'Apply discount code',
            'apply-code-ok-description'         => 'Congratulations! The discount code is valid, you can now benefit from it on your order.',
            'apply-code-ko-title'               => 'Apply discount code',
            'apply-code-ko-description'         => 'The discount code you tried to use is invalid. Try it with another code.',
            'code-no-available-title'           => 'Apply discount code',
            'code-no-available-description'     => 'The discount code you have tried to use is not available. Try with another code.',
            'code-soon-title'                   => 'Apply discount code',
            'code-soon-description'             => 'The discount code you have tried to use is not yet available. Try with another code.',
            'code-expired-title'                => 'Apply discount code',
            'code-expired-description'          => 'The discount code you tried to use has expired. Try with another code.',
            'code-per-user-title'               => 'Apply discount code',
            'code-per-user-description'         => 'You have reached the limit of uses of this code. Try with another code.',
            'code-minimum-title'                => 'Apply discount code',
            'code-minimum-description'          => 'To be able to use this code, the amount of your order must be equal to or greater than ',
            'code-empty-cart-title'             => 'Apply discount code',
            'code-empty-cart-description'       => 'Your code could not be used because your cart is empty.',
            'code-compatible-title'             => 'Apply discount code',
            'code-compatible-description'       => 'The discount code is not compatible with other codes.',
            'code-have-it-title'                => 'Apply discount code',
            'code-have-it-description'          => 'The code is already applied to your cart.',
            'code-registered-title'             => 'Apply discount code',
            'code-registered-description'       => 'You must be registered on the website to be able to use this discount code.'
        )
    );
    
?>