<?php

    define('LANGTXT', array(
            'select'                            => 'Seleccionar',
            'edit'                              => 'Editar',
            'delete'                            => 'Eliminar',
            'telephone'                         => 'Teléfono',
            'error-register'                    => 'Ese email ya esta asociado a otra cuenta',
            'error-login'                       => 'Usuario o contraseña incorrecta',
            'user-fail'                         => 'Este usuario no tiene permisos para acceder',
            'error-login-admin'                 => 'Usuario o contraseña incorrecta',
            'user-admin-fail'                   => 'Este usuario no tiene permisos para acceder',
            'newsletter-ok-title'               => 'Alta realizada con éxito',
            'newsletter-ok-description'         => 'Hemos enviado un email a tu cuenta para que confirmes tu alta en la newsletter. Revisa tu carpeta de spam si no encuentra el email.',
            'error-view-description'            => 'La vista que intenta mostrar no existe.',
            'error-ddbb-description'            => 'Verifique que las variables de conexión sean correctas en el archivo <b>app/config/settings.php</b>.',
            'error-query-description'           => 'Ha ocurrido un error al realizar la consulta a la base de datos, verifique los parámetros.',
            'send-notify-stock'                 => '¡Tu solicitud a sido registrada correctamente!',
            'new-address'                       => 'Necesitas crear una nueva dirección de envío.',
            'new-billing-address'               => 'Necesitas crear una nueva dirección de facturación.',
            'delete-from-cart'                  => 'Eliminar del carrito',
            'cart-empty'                        => 'Tu carrito esta vacío.',
            'newsletter-validation-ok'          => 'Su cuenta ha sido validada correctamente.',
            'newsletter-validation-ko'          => 'Su cuenta no pudo ser validada.',
            'apply-code-ok-title'               => 'Aplicar código de descuento',
            'apply-code-ok-description'         => '¡Enhorabuena! El código de descuento es valido, ya puedes beneficiarte de él en tu pedido.',
            'apply-code-ko-title'               => 'Aplicar código de descuento',
            'apply-code-ko-description'         => 'El código de descuento que has intentado usar no es válido. Inténtalo con otro código.',
            'code-no-available-title'           => 'Aplicar código de descuento',
            'code-no-available-description'     => 'El código de descuento que has intentado usar no esta disponible. Inténtalo con otro código.',
            'code-soon-title'                   => 'Aplicar código de descuento',
            'code-soon-description'             => 'El código de descuento que has intentado usar todavía no esta disponible. Inténtalo con otro código.',
            'code-expired-title'                => 'Aplicar código de descuento',
            'code-expired-description'          => 'El código de descuento que has intentado usar ha expirado. Inténtalo con otro código.',
            'code-per-user-title'               => 'Aplicar código de descuento',
            'code-per-user-description'         => 'Has alcanzado el límite de usos de este código. Inténtalo con otro código.',
            'code-minimum-title'                => 'Aplicar código de descuento',
            'code-minimum-description'          => 'Para poder usar este código importe de tu pedido debe ser igual o superior a ',
            'code-empty-cart-title'             => 'Aplicar código de descuento',
            'code-empty-cart-description'       => 'No se ha podido usar tu código por que tu carrito esta vacío.',
            'code-compatible-title'             => 'Aplicar código de descuento',
            'code-compatible-description'       => 'El código de descuento no es compatible con otros códigos.',
            'code-have-it-title'                => 'Aplicar código de descuento',
            'code-have-it-description'          => 'El código ya esta aplicado a tu carrito.',
            'code-registered-title'             => 'Apply discount code',
            'code-registered-description'       => 'You must be registered on the website to be able to use this discount code.'
        )
    );
    
?>